spring:
  application:
    name: vessel-manager-01
  datasource:
    url: jdbc:postgresql://localhost:5432/vessel_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
